### ISSUE TITLE
Chapter 1: Unexpected token

### ISSUE THREAD

**Issue by Katherine-Reed** [PacktPublishing/React-Projects-Second-Edition#8]
Hi Roy,

I have just completed step 4 on page 10: `npm install --save-dev html-webpack-plugin` and updated *webpack.config.js*. However, when I run `npm start` from the console I receive the following error:

```
ERROR in ./src/index.js 5:8
Module parse failed: Unexpected token (5:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| function App() {
>       return <h1>Rick and Morty</h1>;
| }
|
```

Any help would be appreciated.

**Comment by Packt-Kavyashreek** [comment]
Hi Sgeulaiche,

The error message indicates that there is an issue with parsing JSX syntax in your JavaScript file (index.js) because the file is not being processed correctly by Webpack. JSX is a syntax extension for JavaScript used primarily with React for describing the UI.

To fix this issue, you need to configure Webpack to use a loader that can handle JSX files. You typically use a loader like Babel along with the babel-loader package to transpile JSX code into standard JavaScript code that browsers can understand.

Here's what you need to do:

Install babel-loader and @babel/preset-react if you haven't already:
npm install babel-loader @babel/preset-react --save-dev

Configure Webpack to use babel-loader in your webpack.config.js file:
module.exports = {
  // other webpack configurations...
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader",
          options: {
            presets: ["@babel/preset-react"],
          },
        },
      },
    ],
  },
};

This configuration tells Webpack to use babel-loader for files ending with .js or .jsx, excluding files in the node_modules directory. Additionally, it specifies @babel/preset-react as a preset to enable JSX support.

After making these changes, restart your Webpack build process, and the error should be resolved.
